language: rust
rust:
  - stable
cache: cargo

script:
  - rustup target add x86_64-unknown-linux-gnu
  - rustup target add thumbv7em-none-eabihf

  - cargo check --all-targets --target x86_64-unknown-linux-gnu
  - cargo check --target thumbv7em-none-eabihf --no-default-features # no_std, not for all targets because example needs std

  - cargo test --all-targets --target x86_64-unknown-linux-gnu
